#include "main.h"
#include "stm32f3xx.h"
void init_tim4(void)
{
RCC->APB1ENR |=RCC_APB1ENR_TIM4EN;//RCC(APBTIM4EN)
TIM4->PSC=72;//PSC=7200
TIM4->ARR=0xffffffff;//HRR=1000
TIM4->CR1|=TIM_CR1_CEN;//Enable (CR1)

}
void delay(int time)
{
TIM4->CNT=0;
while(TIM4->CNT<time);
}
int main(void)
{
RCC->AHBENR |= RCC_AHBENR_GPIODEN;
GPIOD->MODER |= GPIO_MODER_MODER1_0;
GPIOD->MODER &=~ GPIO_MODER_MODER1_1;


GPIOD->MODER |= GPIO_MODER_MODER2_0;
GPIOD->MODER &=~ GPIO_MODER_MODER2_1;


GPIOD->MODER |= GPIO_MODER_MODER3_0;
GPIOD->MODER &=~ GPIO_MODER_MODER3_1;


GPIOD->MODER |= GPIO_MODER_MODER4_0;
GPIOD->MODER &=~ GPIO_MODER_MODER4_1;

init_tim4();
		GPIOD->BSRR|= GPIO_BSRR_BR_1;
		GPIOD->BSRR|= GPIO_BSRR_BR_2;
		GPIOD->BSRR|= GPIO_BSRR_BR_3;
		GPIOD->BSRR|= GPIO_BSRR_BR_4;
	while(1)
	{
		GPIOD->BSRR|= GPIO_BSRR_BS_1;
		GPIOD->BSRR|= GPIO_BSRR_BR_2;
		GPIOD->BSRR|= GPIO_BSRR_BR_3;
		GPIOD->BSRR|= GPIO_BSRR_BS_4;
		delay(100);

		GPIOD->BSRR|= GPIO_BSRR_BS_1;
		GPIOD->BSRR|= GPIO_BSRR_BR_2;
		GPIOD->BSRR|= GPIO_BSRR_BR_3;
		GPIOD->BSRR|= GPIO_BSRR_BR_4;
		delay(100);
			GPIOD->BSRR|= GPIO_BSRR_BS_1;
			GPIOD->BSRR|= GPIO_BSRR_BS_2;
			GPIOD->BSRR|= GPIO_BSRR_BR_3;
			GPIOD->BSRR|= GPIO_BSRR_BR_4;
			delay(100);
				GPIOD->BSRR|= GPIO_BSRR_BR_1;
				GPIOD->BSRR|= GPIO_BSRR_BS_2;
				GPIOD->BSRR|= GPIO_BSRR_BR_3;
				GPIOD->BSRR|= GPIO_BSRR_BR_4;
				delay(100);
					GPIOD->BSRR|= GPIO_BSRR_BR_1;
					GPIOD->BSRR|= GPIO_BSRR_BS_2;
					GPIOD->BSRR|= GPIO_BSRR_BS_3;
					GPIOD->BSRR|= GPIO_BSRR_BR_4;
					delay(100);
						GPIOD->BSRR|= GPIO_BSRR_BR_1;
						GPIOD->BSRR|= GPIO_BSRR_BR_2;
						GPIOD->BSRR|= GPIO_BSRR_BS_3;
						GPIOD->BSRR|= GPIO_BSRR_BR_4;
						delay(100);
							GPIOD->BSRR|= GPIO_BSRR_BR_1;
							GPIOD->BSRR|= GPIO_BSRR_BR_2;
							GPIOD->BSRR|= GPIO_BSRR_BS_3;
							GPIOD->BSRR|= GPIO_BSRR_BS_4;
							delay(100);
								GPIOD->BSRR|= GPIO_BSRR_BR_1;
								GPIOD->BSRR|= GPIO_BSRR_BR_2;
								GPIOD->BSRR|= GPIO_BSRR_BR_3;
								GPIOD->BSRR|= GPIO_BSRR_BS_4;
								delay(100);


	}




}